<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--  基础数据  -->
    <modules>
        <module>genchuan-module-waterdetection</module>
    </modules>

    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>genchuan-module-wateraffairs</artifactId>
    <packaging>pom</packaging>

    <name>genchuan-module-wateraffairs</name>
    <url>http://maven.apache.org</url>

    <description>
        行业应用——水利水务模块，主要实现 XXX、YYY、ZZZ 等功能。
    </description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
