-- 充电停车一体化管理系统 - 订单交易模块 建表SQL（新版）
CREATE DATABASE IF NOT EXISTS `order_trade` DEFAULT CHARACTER SET utf8mb4;
USE `order_trade`;

CREATE TABLE IF NOT EXISTS `all_order` (
                                           `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                           `order_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '订单编号',
    `order_type` VARCHAR(20) NOT NULL COMMENT '订单类型：临时停车/错时停车/汽车充电/两轮充电/共享充电',
    `plate_no` VARCHAR(16) COMMENT '车牌',
    `amount` DECIMAL(10,2) NOT NULL COMMENT '订单金额',
    `status` VARCHAR(20) NOT NULL COMMENT '支付状态：待支付/已支付/已完成/已取消',
    `create_order_time` DATETIME NOT NULL COMMENT '订单生成时间',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `pay_time` DATETIME COMMENT '支付时间',
    `pay_method` VARCHAR(20) COMMENT '支付方式：微信/支付宝/银行卡/现金',
    `discount_amount` DECIMAL(10,2) COMMENT '优惠抵扣金额',
    `archive_time` DATETIME COMMENT '归档时间',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='全部订单';

CREATE TABLE IF NOT EXISTS `temp_park_order` (
                                                 `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                                 `order_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '订单编号',
    `plate_no` VARCHAR(16) NOT NULL COMMENT '车牌',
    `park_duration` INT NOT NULL COMMENT '停车时长（分钟）',
    `amount` DECIMAL(10,2) NOT NULL COMMENT '订单金额',
    `status` VARCHAR(20) NOT NULL COMMENT '支付状态',
    `create_order_time` DATETIME NOT NULL COMMENT '订单生成时间',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `pay_time` DATETIME COMMENT '支付时间',
    `pay_method` VARCHAR(20) COMMENT '支付方式',
    `discount_amount` DECIMAL(10,2) COMMENT '优惠抵扣金额',
    `archive_time` DATETIME COMMENT '归档时间',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='临时停车订单';

CREATE TABLE IF NOT EXISTS `offtime_park_order` (
                                                    `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                                    `order_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '订单编号',
    `plate_no` VARCHAR(16) NOT NULL COMMENT '车牌',
    `reserve_start_time` DATETIME NOT NULL COMMENT '预约开始时间',
    `reserve_end_time` DATETIME NOT NULL COMMENT '预约结束时间',
    `actual_start_time` DATETIME COMMENT '实际使用开始时间',
    `actual_end_time` DATETIME COMMENT '实际使用结束时间',
    `amount` DECIMAL(10,2) NOT NULL COMMENT '订单金额',
    `status` VARCHAR(20) NOT NULL COMMENT '支付状态',
    `create_order_time` DATETIME NOT NULL COMMENT '订单生成时间',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `pay_time` DATETIME COMMENT '支付时间',
    `pay_method` VARCHAR(20) COMMENT '支付方式',
    `archive_time` DATETIME COMMENT '归档时间',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='错时停车订单';

CREATE TABLE IF NOT EXISTS `car_charge_order` (
                                                  `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                                  `order_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '订单编号',
    `plate_no` VARCHAR(16) NOT NULL COMMENT '车牌',
    `charge_duration` INT NOT NULL DEFAULT 0 COMMENT '充电时长（分钟）',
    `charge_quantity` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '充电量（度）',
    `charge_power` DECIMAL(10,2) COMMENT '充电功率（kw）',
    `amount` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '订单金额',
    `status` VARCHAR(20) NOT NULL COMMENT '订单状态：充电中/待支付/已支付/已完成/已取消',
    `create_order_time` DATETIME NOT NULL COMMENT '订单生成时间',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `pay_time` DATETIME COMMENT '支付时间',
    `pay_method` VARCHAR(20) COMMENT '支付方式',
    `discount_amount` DECIMAL(10,2) COMMENT '优惠抵扣金额',
    `archive_time` DATETIME COMMENT '归档时间',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='汽车充电订单';

CREATE TABLE IF NOT EXISTS `bike_charge_order` (
                                                   `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                                   `order_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '订单编号',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `user_nickname` VARCHAR(64) NOT NULL COMMENT '用户昵称',
    `charge_duration` INT NOT NULL DEFAULT 0 COMMENT '充电时长（分钟）',
    `charge_quantity` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '充电量（度）',
    `amount` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '订单金额',
    `status` VARCHAR(20) NOT NULL COMMENT '订单状态：充电中/待支付/已支付/已完成/已取消',
    `create_order_time` DATETIME NOT NULL COMMENT '订单生成时间',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `pay_time` DATETIME COMMENT '支付时间',
    `pay_method` VARCHAR(20) COMMENT '支付方式',
    `discount_amount` DECIMAL(10,2) COMMENT '优惠抵扣金额',
    `archive_time` DATETIME COMMENT '归档时间',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='两轮充电订单';

CREATE TABLE IF NOT EXISTS `share_charge_order` (
                                                    `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                                    `order_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '订单编号',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `user_nickname` VARCHAR(64) NOT NULL COMMENT '用户昵称',
    `lend_time` DATETIME NOT NULL COMMENT '借出时间',
    `return_time` DATETIME COMMENT '归还时间',
    `actual_duration` INT COMMENT '实际使用时长（分钟）',
    `amount` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '订单金额',
    `status` VARCHAR(20) NOT NULL COMMENT '订单状态：借出中/待支付/已支付/已完成/已取消',
    `create_order_time` DATETIME NOT NULL COMMENT '订单生成时间',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `pay_method` VARCHAR(20) COMMENT '支付方式',
    `discount_amount` DECIMAL(10,2) COMMENT '优惠抵扣金额',
    `archive_time` DATETIME COMMENT '归档时间',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='共享充电订单';

CREATE TABLE IF NOT EXISTS `abnormal_order` (
                                                `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                                `order_id` BIGINT NOT NULL COMMENT '关联订单ID',
                                                `order_type` VARCHAR(20) NOT NULL COMMENT '订单类型',
    `abnormal_type` VARCHAR(20) NOT NULL COMMENT '异常类型：支付异常/计费异常/状态异常',
    `identify_time` DATETIME NOT NULL COMMENT '异常识别时间',
    `status` VARCHAR(20) NOT NULL COMMENT '处置状态：未处理/处理中/已关闭',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `ignore_reason` TEXT COMMENT '忽略理由',
    `process_progress` TEXT COMMENT '处置进度',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='异常订单';

CREATE TABLE IF NOT EXISTS `debt_identify` (
                                               `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                               `identify_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '识别编号',
    `plate_no` VARCHAR(16) NOT NULL COMMENT '车牌',
    `arrear_amount` DECIMAL(10,2) NOT NULL COMMENT '欠费金额',
    `identify_time` DATETIME NOT NULL COMMENT '识别时间',
    `status` VARCHAR(20) NOT NULL COMMENT '状态：待识别/已识别',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='逃费识别';

CREATE TABLE IF NOT EXISTS `debt_record` (
                                             `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                             `record_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '记录编号',
    `plate_no` VARCHAR(16) NOT NULL COMMENT '车牌',
    `arrear_order_count` INT NOT NULL COMMENT '欠费订单数',
    `arrear_amount` DECIMAL(10,2) NOT NULL COMMENT '欠费金额',
    `status` VARCHAR(20) NOT NULL COMMENT '追缴状态：未追缴/追缴中/已完成',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `collect_progress` TEXT COMMENT '追缴进度',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='逃费记录';

CREATE TABLE IF NOT EXISTS `arrear_record` (
                                               `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                               `record_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '记录编号',
    `plate_no` VARCHAR(16) NOT NULL COMMENT '车牌',
    `order_ids` VARCHAR(255) NOT NULL COMMENT '关联欠费订单ID',
    `arrear_amount` DECIMAL(10,2) NOT NULL COMMENT '欠费金额',
    `status` VARCHAR(20) NOT NULL COMMENT '结清状态：未结清/已结清',
    `station_id` BIGINT NOT NULL COMMENT '所属场站ID',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='欠费记录';

CREATE TABLE IF NOT EXISTS `collect_track` (
                                               `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                               `track_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '追缴编号',
    `plate_no` VARCHAR(16) NOT NULL COMMENT '车牌',
    `collect_method` VARCHAR(20) NOT NULL COMMENT '追缴方式：短信/站内信/电话',
    `collect_time` DATETIME NOT NULL COMMENT '追缴时间',
    `status` VARCHAR(20) NOT NULL COMMENT '状态：待推送/追缴中/已完成',
    `area_id` BIGINT NOT NULL COMMENT '片区ID（关联system_dept）',
    `transfer_user_id` BIGINT COMMENT '转派用户ID',
    `collect_progress` TEXT COMMENT '追缴进度',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='追缴跟踪';

CREATE TABLE IF NOT EXISTS `collect_config` (
                                                `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                                `config_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '配置编号',
    `collect_method` VARCHAR(20) NOT NULL COMMENT '追缴方式：短信/站内信/电话',
    `template_id` BIGINT NOT NULL COMMENT '推送模板ID',
    `push_frequency` INT NOT NULL COMMENT '推送频次（小时）',
    `status` VARCHAR(20) NOT NULL COMMENT '状态：未生效/已生效',
    `remark` TEXT COMMENT '配置说明',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='追缴配置';

CREATE TABLE IF NOT EXISTS `refund_apply` (
                                              `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                              `apply_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '申请编号',
    `order_id` BIGINT NOT NULL COMMENT '关联订单ID',
    `refund_amount` DECIMAL(10,2) NOT NULL COMMENT '退款金额',
    `refund_reason` TEXT NOT NULL COMMENT '退款原因',
    `apply_time` DATETIME NOT NULL COMMENT '申请时间',
    `status` VARCHAR(20) NOT NULL COMMENT '状态：待审核/待执行/已完成/已驳回',
    `applicant_id` BIGINT NOT NULL COMMENT '申请人ID',
    `audit_user_id` BIGINT COMMENT '审核人ID',
    `audit_time` DATETIME COMMENT '审核时间',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款申请';

CREATE TABLE IF NOT EXISTS `refund_record` (
                                               `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                               `record_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '记录编号',
    `apply_id` BIGINT NOT NULL COMMENT '关联退款申请ID',
    `order_id` BIGINT NOT NULL COMMENT '关联订单ID',
    `refund_amount` DECIMAL(10,2) NOT NULL COMMENT '退款金额',
    `refund_time` DATETIME NOT NULL COMMENT '退款时间',
    `status` VARCHAR(20) NOT NULL COMMENT '状态：正常记录/异常记录',
    `check_reason` TEXT COMMENT '核查理由',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退款记录';

CREATE TABLE IF NOT EXISTS `amount_check` (
                                              `id`  BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                              `check_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '核算编号',
    `order_id` BIGINT NOT NULL COMMENT '关联订单ID',
    `apply_amount` DECIMAL(10,2) NOT NULL COMMENT '申请金额',
    `check_result` VARCHAR(20) COMMENT '核算结果：通过/不通过',
    `check_detail` TEXT COMMENT '核算明细',
    `status` VARCHAR(20) NOT NULL COMMENT '状态：待核算/已核算',
    `operator_id` BIGINT COMMENT '操作人ID',
    `reserve1`     VARCHAR(100)  COMMENT '备用字段1',
    `reserve2`     VARCHAR(100)  COMMENT '备用字段2',
    `creator`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建者',
    `updater`      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新者',
    `deleted`      BIT(1)        NOT NULL DEFAULT 0  COMMENT '删除标识',
    `tenant_id`    BIGINT        NOT NULL DEFAULT 1  COMMENT '租户ID',
    `create_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='金额核算';

