<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>genchuan-module-urban</artifactId>
        <groupId>cn.iocoder.cloud</groupId>
        <version>${revision}</version> <!-- 1. 修改 version 为 ${revision} -->
    </parent>

    <artifactId>genchuan-module-smartcity</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        顺昌智慧城管演示系统
    </description>

    <modules>
        <module>genchuan-module-smartcity-api</module>
        <module>genchuan-module-smartcity-server</module>
    </modules>

</project>