apiVersion: apps/v1
kind: Deployment
metadata:
  name: yudao-gateway
  namespace: test
  labels:
    app: yudao-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yudao-gateway
  template:
    metadata:
      labels:
        app: yudao-gateway
    spec:
      containers:
      - name: yudao-gateway
        image: harbor.genchuan.cn/sccsgl/yudao-gateway:laster
        imagePullPolicy: Always
        ports:
        - containerPort: 48080
      env:
        - name: NACOS_SERVER_ADDR
          value: 192.168.8.11:31591
        - name: NACOS_NAMESPACE
          value: dev
        - name: NACOS_USERNAME
          value: 
        - name: NACOS_PASSWORD
          value:
---
apiVersion: v1
kind: Service
metadata:
  name: yudao-gateway
  namespace: test
spec:
  selector:
    app: yudao-gateway
  ports:
    - protocol: TCP
      port: 48080
      targetPort: 48080
  type: NodePort