<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>genchuan-module-chargepark</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>genchuan-module-usermerchant</artifactId>
    <packaging>pom</packaging>

    <name>${artifactId}</name>
    <description>
        用户商户模块，主要实现用户商户管理功能。
    </description>
    <url>http://maven.apache.org</url>
    <modules>
        <module>genchuan-module-usermerchant-api</module>
        <module>genchuan-module-usermerchant-server</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
